import * as ydAccordion from "./components/ydAccordion"
import * as ydActionSheet from "./components/ydActionSheet"
import * as ydBackTop from "./components/ydBackTop"
import * as ydBadge from "./components/ydBadge"
import * as ydButton from "./components/ydButton"
import * as ydCell from "./components/ydCell"
import * as ydCheckBox from "./components/ydCheckBox"
import * as ydCheckList from "./components/ydCheckList"
import * as ydCitySelect from "./components/ydCitySelect"
import * as ydCountDown from "./components/ydCountDown"
import * as ydCountUp from "./components/ydCountUp"
import * as ydDateTime from "./components/ydDateTime"
import * as ydFlexBox from "./components/ydFlexBox"
import * as ydGrids from "./components/ydGrids"
import * as ydIcons from "./components/ydIcons"
import * as ydInfiniteScroll from "./components/ydInfiniteScroll"
import * as ydInput from "./components/ydInput"
import * as ydKeyBoard from "./components/ydKeyBoard"
import * as ydLayout from "./components/ydLayout"
import * as ydLightBox from "./components/ydLightBox"
import * as ydList from "./components/ydList"
import * as ydNavbar from "./components/ydNavbar"
import * as ydPopup from "./components/ydPopup"
import * as ydPreview from "./components/ydPreview"
import * as ydProgressBar from "./components/ydProgressBar"
import * as ydPullRefresh from "./components/ydPullRefresh"
import * as ydRadio from "./components/ydRadio"
import * as ydRate from "./components/ydRate"
import * as ydRollNotice from "./components/ydRollNotice"
import * as ydScrollNav from "./components/ydScrollNav"
import * as ydScrollTab from "./components/ydScrollTab"
import * as ydSearch from "./components/ydSearch"
import * as ydSendCode from "./components/ydSendCode"
import * as ydSlider from "./components/ydSlider"
import * as ydSpinner from "./components/ydSpinner"
import * as ydStep from "./components/ydStep"
import * as ydSwitch from "./components/ydSwitch"
import * as ydTab from "./components/ydTab"
import * as ydTabbar from "./components/ydTabbar"
import * as ydTextarea from "./components/ydTextarea"
import * as ydTimeLine from "./components/ydTimeLine"

export const ydComponent = {
	...ydAccordion, ...ydActionSheet, ...ydBackTop, ...ydBadge, ...ydButton, ...ydCell, ...ydCheckBox, ...ydCheckList, ...ydCitySelect, ...ydCountDown, ...ydCountUp, ...ydDateTime, ...ydFlexBox, ...ydGrids, ...ydIcons, ...ydInfiniteScroll, ...ydInput, ...ydKeyBoard, ...ydLayout, ...ydLightBox, ...ydList, ...ydNavbar, ...ydPopup, ...ydPreview, ...ydProgressBar, ...ydPullRefresh, ...ydRadio, ...ydRate, ...ydRollNotice, ...ydScrollNav, ...ydScrollTab, ...ydSearch, ...ydSendCode, ...ydSlider, ...ydSpinner, ...ydStep, ...ydSwitch, ...ydTab, ...ydTabbar, ...ydTextarea, ...ydTimeLine
}

export const ydComponentName = ["Button","ButtonGroup","CellGroup","CellItem","Icons","ListTheme","ListItem","ListOther","Badge","GridsGroup","GridsItem","NavBar","NavBarBackIcon","NavBarNextIcon","TabBar","TabBarItem","Layout","TextArea","Input","FlexBox","FlexBoxItem","Switch","Radio","RadioGroup","CheckBox","CheckBoxGroup","TimeLine","TimeLineItem","Step","StepItem","Preview","PreviewHeader","PreviewItem","Confirm","Alert","Toast","Notify","Loading","Slider","SliderItem","ProgressBar","ActionSheet","Tab","TabPanel","ScrollTab","ScrollTabPanel","KeyBoard","Spinner","SendCode","CitySelect","InfiniteScroll","PullRefresh","CountDown","CountUp","Rate","Popup","RollNotice","RollNoticeItem","BackTop","Accordion","AccordionItem","DateTime","LightBox","LightBoxImg","LightBoxTxt","CheckList","CheckListItem","Search","ScrollNav","ScrollNavPanel"];